### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by arsschematica** [andybywire/cfp-example#3]
Hello Andy. I really like this idea and wanted to test it out on my computer, but the build keeps failing. I am on a windows machine; which I fear might be the reason. Installing Ruby, `gem install jekyll`, and `npm install` went without problems, but below is the output of `npm start`. What I gather from this is that Jekyll failed, but I don't know why or how to figure out why. I can not even find `events.js`.

Any help would be appreciated.

``` sh
[19:53:41] Using gulpfile ~\Downloads\cfp-example-master\cfp-example-master\gulpfile.js
[19:53:41] Starting 'default'...
[19:53:41] Starting 'json'...
[19:53:41] Finished 'json' after 8.48 ms
[19:53:41] Starting 'sass'...
[19:55:51] Finished 'sass' after 2.15 min
[19:55:51] Starting 'jekyll'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! content-first-prototyping@1.0.0 start: `gulp`
npm ERR! Exit status 1
```

**Comment by andybywire** [comment]
Hi!
Thanks for filing this issue. I had seen the `throw er; // Unhandled 'error' event` error in developing the framework, but haven't seen it for quite a while – and, unfortunately, don't know right off where this one is coming from. 
I can dig into it on Windows, but let's verify one thing first: are you using the version of the repo that corrects the bug that capturecadet found: https://github.com/andybywire/cfp-example/issues/1? If not, try fixing that first. You might find it easier to just update the `_config.yml` file based on this diff: https://github.com/andybywire/cfp-example/commit/8a7e5f6c8a859951a646a2770f8b4d1dadeb769a
Do let me know how that goes! I'm glad to hear you want to try out the framework and am happy to help get it working for you.
